# Generated by Django 4.2.8 on 2024-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="shelter",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("type", models.CharField(blank=True, max_length=200)),
                ("location", models.TextField(blank=True, max_length=200)),
                ("contact", models.CharField(blank=True, max_length=200)),
                ("size", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
